### ISSUE TITLE
Could it support comment line for ASM/PY/Batch files?

### ISSUE THREAD

**Issue by mungooboy** [wujingbo/Source-Insight-4.0-for-edk2#1]
Here are two function support same file type to work in Comment Macros.em  
//   1. Comment Selected Lines (Alt+C)
//   2. Un-Comment Selected Lines (Alt+R)

Would you have any plan to support more file type?

**Comment by wujingbo** [comment]
Sure, but python(*.py) language already be supported by default.
The other 2 file type(*.asm, *.bat), I'm going to implement them recently.
